# Generated by Django 4.1 on 2022-10-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_newusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newusers',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
