# Generated by Django 4.1 on 2022-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_texts_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
