# Generated by Django 4.1 on 2022-10-31 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_texts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
